// app/metadata.ts
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Shri Harihareshwara Temple, Hariharapallathadka',
  description: 'Explore the spiritual heritage of Shri Harihareshwara Temple in Hariharapallathadka, Karnataka. Discover its rich history, unique architecture, and religious significance.',
  keywords: [
    'Shri Harihareshwara Temple',
    'Hariharapallathadka',
    'Karnataka temples',
    'Lord Harihara',
    'Vishnu and Shiva',
    'Hindu pilgrimage',
    'Triveni Sangam',
    'Tula Sankramana',
    'Shani Pooja',
    'sacred confluence',
    'spiritual tourism',
    'Kukke Subrahmanya',
    'Subrahmanya',
    'Kulkunda',
    'Kulkunda Shree Basaveshwara Temple',
    'Kulkunda Shri Basaveshwara Temple',
    'Basavanamoola',
    'Basavanamoola Shree Basaveshwara Temple',
    'Basavanamoola Shri Basaveshwara Temple',
    'Shri Harihareshwara Temple',
    'Shree Harihareshwara Temple',
    'Sri Harihareshwara Temple',
    'Shri Harihareshwara Temple Hariharapallathadka',
    'Shree Harihareshwara Temple Hariharapallathadka',
    'Rudrabhishekam',
    'Lord Shiva',
    'Lord Vishnu',
    'Lord Mahaganapathi',
    'Lord Ganesha',
    'Lord Subrahmanya',
  ],
  authors: [{ name: 'Shri Harihareshwara Temple Trust' }],
  openGraph: {
    title: 'Shri Harihareshwara Temple, Hariharapallathadka',
    description: 'Discover the divine amalgamation of Lord Vishnu and Lord Shiva at Shri Harihareshwara Temple in Hariharapallathadka, Karnataka. Learn about its historical legends, architectural marvels, and religious festivals.',
    url: 'www.shriharihareshwara.org',
    siteName: 'Shri Harihareshwara Temple',
    images: [
      {
        url: '/logo.jpg',
        width: 800,
        height: 600,
        alt: 'Shri Harihareshwara Temple',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Shri Harihareshwara Temple, Hariharapallathadka',
    description: 'Explore the spiritual heritage of Shri Harihareshwara Temple in Hariharapallathadka, Karnataka. Discover its rich history, unique architecture, and religious significance.',
    images: ['https://example.com/path-to-your-image.jpg'],
  },
  icons: {
    icon: '/path-to-your-favicon.ico',
  },
};
