// app/metadata.ts
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Shri Harihareshwara Temple, Hariharapallathadka',
  description: 'Explore the spiritual heritage of Shri Harihareshwara Temple in Hariharapallathadka, Karnataka. Discover its rich history, unique architecture, and religious significance.',
  keywords: [
    'Shri Harihareshwara Temple',
    'Hariharapallathadka',
    'Karnataka temples',
    'Lord Harihara',
    'Vishnu and Shiva',
    'Hindu pilgrimage',
    'Triveni Sangam',
    'Tula Sankramana',
    'Shani Pooja',
    'sacred confluence',
    'spiritual tourism',
    'Kukke Subrahmanya',
    'Subrahmanya',
    'Kulkunda',
    'Kulkunda Shree Basaveshwara Temple',
    'Kulkunda Shri Basaveshwara Temple',
    'Basavanamoola',
    'Basavanamoola Shree Basaveshwara Temple',
    'Basavanamoola Shri Basaveshwara Temple',
    'Shri Harihareshwara Temple',
    'Shree Harihareshwara Temple',
    'Sri Harihareshwara Temple',
    'Shri Harihareshwara Temple Hariharapallathadka',
    'Shree Harihareshwara Temple Hariharapallathadka',
    'Rudrabhishekam',
    'Lord Shiva',
    'Lord Vishnu',
    'Lord Mahaganapathi',
    'Lord Ganesha',
    'Lord Subrahmanya',
    'Champashasti',
    'Shree Basaveshwara Temple, Hindu temple, Basavanamoola, Kulkunda, Lord Shiva, Kukke Subrahmanya,Kukke Shree Subrahmanya Temple, sacred place, cultural significance,historical place,Bisle Ghats,Tulunadu,Temples in Coastal Karnataka,Temples in Kukke Subrahmanya,Nearby places in Subrahmanya,places to visit,places to visit at Subrahmanya,Nearby temples to Kukke Shri Subrahmanya Temple,Dharmasthala,Shri Kshethra Dharmasthala,Kulkunda Shree Basaveshwara Temple, Kukke Shri Subrahmanya Temple, Adi Subrahmanya Temple, Shri Subrahmanya Mutt, Kashikatte Shri Ganapathi Temple, Biladwara, Shri Vanadurga Devi Temple, Shree Abhaya Mahaganapathi, Agrahara Shri Somanatha Temple, Shree Harihareshwara Temple, Kumaradhara River (Bathing Ghat), Shri Kshethra Dharmasthala, Bisle Ghat Viewpoint, Patla Betta, Mallalli Falls, Hindu temples, Karnataka, Western Ghats, Serpent king Vasuki, Kumaraparvatha, Dharmasthala Manjunatha Swamy Temple, Free meals, Jain Pergade family, Bisle Ghat, Somwarpet, Coorg, Monsoon season, Nature enthusiasts, Trekkers,Kumara Parvatha trek,Kumara Parvatha trekking,Shesha Parvatha,South India treks,South India Temples,Karnataka Hikers,Karnataka Trekkers,Bhattaramane,Bhattas house,Bhattara Mane,Treks in Karnataka,Treks in Western Ghats,Treks in South India,Toughest treks, Western Ghats landscapes'
  ],
  authors: [{ name: 'Shri Harihareshwara Temple Trust' }],
  openGraph: {
    title: 'Shri Harihareshwara Temple, Hariharapallathadka',
    description: 'Discover the divine amalgamation of Lord Vishnu and Lord Shiva at Shri Harihareshwara Temple in Hariharapallathadka, Karnataka. Learn about its historical legends, architectural marvels, and religious festivals.',
    url: 'www.shriharihareshwara.org',
    siteName: 'Shri Harihareshwara Temple',
    images: [
      {
        url: '/logo.jpg',
        width: 800,
        height: 600,
        alt: 'Shri Harihareshwara Temple',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Shri Harihareshwara Temple, Hariharapallathadka',
    description: 'Explore the spiritual heritage of Shri Harihareshwara Temple in Hariharapallathadka, Karnataka. Discover its rich history, unique architecture, and religious significance.',
    images: ['https://example.com/path-to-your-image.jpg'],
  },
  icons: {
    icon: '/path-to-your-favicon.ico',
  },
};
